#!/usr/bin/env node
// Interactive setup for Remote Coding Agents.
//
// Run after cloning:
//   node scripts/setup.mjs
//
// What it does (interactively, with chances to skip each):
//   1. Verifies Node >= 20 and Docker is reachable
//   2. Seeds .env from .env.example, optionally prompting for ports / API key
//   3. Installs npm dependencies (root + workspaces)
//   4. Builds the agent Docker image
//   5. Offers to launch `npm run dev`

import { spawn, spawnSync } from "node:child_process";
import { existsSync, copyFileSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..");
const envFile = path.join(repoRoot, ".env");
const envExample = path.join(repoRoot, ".env.example");

// Bootstrap: @clack/prompts is a root devDep, so on a fresh clone it isn't
// available until `npm install` has run. Try to import it; if it's missing,
// run `npm install` first (with plain console output) and then import.
async function loadClack() {
  try {
    return await import("@clack/prompts");
  } catch (err) {
    if (err && err.code !== "ERR_MODULE_NOT_FOUND") throw err;
  }
  console.log(
    "\x1b[36m›\x1b[39m First run — installing dependencies before the interactive setup starts.",
  );
  console.log("  (This step only happens once.)\n");
  const res = spawnSync(
    "npm",
    ["install", "--workspaces", "--include-workspace-root", "--no-fund", "--no-audit"],
    {
      cwd: repoRoot,
      stdio: "inherit",
      shell: process.platform === "win32",
    },
  );
  if (res.status !== 0) {
    console.error(
      "\x1b[31m✗ npm install failed.\x1b[39m Fix the error above, then re-run `node scripts/setup.mjs`.",
    );
    process.exit(res.status ?? 1);
  }
  console.log();
  return import("@clack/prompts");
}

const {
  intro,
  outro,
  text,
  confirm,
  select,
  spinner,
  log,
  cancel,
  isCancel,
  note,
  group,
} = await loadClack();

const color = {
  dim: (s) => `\x1b[2m${s}\x1b[22m`,
  cyan: (s) => `\x1b[36m${s}\x1b[39m`,
  green: (s) => `\x1b[32m${s}\x1b[39m`,
  red: (s) => `\x1b[31m${s}\x1b[39m`,
};

function bailOnCancel(value) {
  if (isCancel(value)) {
    cancel("Setup cancelled.");
    process.exit(0);
  }
  return value;
}

function which(cmd) {
  const res = spawnSync(process.platform === "win32" ? "where" : "which", [cmd], {
    encoding: "utf8",
  });
  return res.status === 0 ? res.stdout.trim().split(/\r?\n/)[0] : null;
}

function exec(cmd, args, opts = {}) {
  return new Promise((resolve) => {
    const child = spawn(cmd, args, {
      stdio: opts.inherit ? "inherit" : "pipe",
      cwd: opts.cwd ?? repoRoot,
      env: process.env,
      shell: process.platform === "win32",
    });
    let stdout = "";
    let stderr = "";
    if (!opts.inherit) {
      child.stdout?.on("data", (d) => (stdout += d.toString()));
      child.stderr?.on("data", (d) => (stderr += d.toString()));
    }
    child.on("close", (code) => resolve({ code: code ?? 1, stdout, stderr }));
    child.on("error", (err) => resolve({ code: 1, stdout, stderr: String(err) }));
  });
}

async function checkNode() {
  const v = process.versions.node;
  const major = Number.parseInt(v.split(".")[0], 10);
  if (major < 20) {
    log.error(`Node ${v} found — this project needs Node 20 or newer.`);
    return false;
  }
  log.success(`Node ${v} ✓`);
  return true;
}

async function checkDocker() {
  if (!which("docker")) {
    log.error("Docker CLI not found on PATH.");
    return false;
  }
  const s = spinner();
  s.start("Pinging Docker daemon...");
  const res = await exec("docker", ["info", "--format", "{{.ServerVersion}}"]);
  if (res.code !== 0) {
    s.stop("Docker daemon unreachable.");
    log.error(res.stderr.trim() || "could not reach docker. Is Docker Desktop running?");
    return false;
  }
  s.stop(`Docker ✓ (server ${res.stdout.trim()})`);
  return true;
}

function readDotEnv() {
  if (!existsSync(envFile)) return {};
  const txt = readFileSync(envFile, "utf8");
  const out = {};
  for (const line of txt.split(/\r?\n/)) {
    const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/.exec(line);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

function writeDotEnv(values) {
  const lines = [
    "# Generated by scripts/setup.mjs — edit freely.",
    `SERVER_PORT=${values.SERVER_PORT}`,
    `CLIENT_PORT=${values.CLIENT_PORT}`,
    `PROJECTS_ROOT=${values.PROJECTS_ROOT}`,
    `DATA_ROOT=${values.DATA_ROOT}`,
    `AGENT_IMAGE=${values.AGENT_IMAGE}`,
    `DOCKER_HOST_WORKSPACE_ROOT=${values.DOCKER_HOST_WORKSPACE_ROOT ?? ""}`,
    `DOCKER_HOST_PROJECTS_ROOT=${values.DOCKER_HOST_PROJECTS_ROOT ?? ""}`,
    `TTYD_PORT_MIN=${values.TTYD_PORT_MIN}`,
    `TTYD_PORT_MAX=${values.TTYD_PORT_MAX}`,
    "",
    "# Agent credentials — only the key matching the chosen agent is forwarded.",
    `ANTHROPIC_API_KEY=${values.ANTHROPIC_API_KEY ?? ""}`,
    `OPENAI_API_KEY=${values.OPENAI_API_KEY ?? ""}`,
    `GEMINI_API_KEY=${values.GEMINI_API_KEY ?? ""}`,
    `GITHUB_TOKEN=${values.GITHUB_TOKEN ?? ""}`,
  ];
  writeFileSync(envFile, lines.join("\n") + "\n", "utf8");
}

async function configureEnv() {
  if (!existsSync(envExample)) {
    log.error("Missing .env.example — repo looks broken.");
    return null;
  }
  if (!existsSync(envFile)) {
    copyFileSync(envExample, envFile);
    log.success("Seeded .env from .env.example");
  } else {
    log.info(".env already exists; keeping current values and only filling gaps.");
  }
  const current = readDotEnv();

  const answers = bailOnCancel(
    await group(
      {
        SERVER_PORT: () =>
          text({
            message: "Backend HTTP port",
            initialValue: current.SERVER_PORT ?? "4000",
            validate: (v) => (/^\d+$/.test(v) ? undefined : "must be a number"),
          }),
        CLIENT_PORT: () =>
          text({
            message: "Frontend dev port (Vite)",
            initialValue: current.CLIENT_PORT ?? "5173",
            validate: (v) => (/^\d+$/.test(v) ? undefined : "must be a number"),
          }),
        TTYD_PORT_MIN: () =>
          text({
            message: "ttyd port range (min)",
            initialValue: current.TTYD_PORT_MIN ?? "7700",
            validate: (v) => (/^\d+$/.test(v) ? undefined : "must be a number"),
          }),
        TTYD_PORT_MAX: () =>
          text({
            message: "ttyd port range (max)",
            initialValue: current.TTYD_PORT_MAX ?? "7800",
            validate: (v) => (/^\d+$/.test(v) ? undefined : "must be a number"),
          }),
        ANTHROPIC_API_KEY: () =>
          text({
            message: "ANTHROPIC_API_KEY (Claude — leave blank to skip)",
            placeholder: "sk-ant-...",
            initialValue: current.ANTHROPIC_API_KEY ?? "",
          }),
        OPENAI_API_KEY: () =>
          text({
            message: "OPENAI_API_KEY (Codex — leave blank to skip)",
            placeholder: "sk-...",
            initialValue: current.OPENAI_API_KEY ?? "",
          }),
        GEMINI_API_KEY: () =>
          text({
            message: "GEMINI_API_KEY (Gemini — leave blank to skip)",
            placeholder: "AIza...",
            initialValue: current.GEMINI_API_KEY ?? "",
          }),
        GITHUB_TOKEN: () =>
          text({
            message: "GITHUB_TOKEN (Copilot — leave blank to skip)",
            placeholder: "ghp_...",
            initialValue: current.GITHUB_TOKEN ?? "",
          }),
      },
      { onCancel: () => bailOnCancel("__cancel__") },
    ),
  );

  const merged = {
    SERVER_PORT: answers.SERVER_PORT.trim(),
    CLIENT_PORT: answers.CLIENT_PORT.trim(),
    PROJECTS_ROOT: current.PROJECTS_ROOT ?? "./projects",
    DATA_ROOT: current.DATA_ROOT ?? "./data",
    AGENT_IMAGE: current.AGENT_IMAGE ?? "rca-agent:latest",
    DOCKER_HOST_WORKSPACE_ROOT: current.DOCKER_HOST_WORKSPACE_ROOT ?? "",
    DOCKER_HOST_PROJECTS_ROOT: current.DOCKER_HOST_PROJECTS_ROOT ?? "",
    TTYD_PORT_MIN: answers.TTYD_PORT_MIN.trim(),
    TTYD_PORT_MAX: answers.TTYD_PORT_MAX.trim(),
    ANTHROPIC_API_KEY: (answers.ANTHROPIC_API_KEY ?? "").trim(),
    OPENAI_API_KEY: (answers.OPENAI_API_KEY ?? "").trim(),
    GEMINI_API_KEY: (answers.GEMINI_API_KEY ?? "").trim(),
    GITHUB_TOKEN: (answers.GITHUB_TOKEN ?? "").trim(),
  };
  writeDotEnv(merged);
  log.success(`Wrote ${path.relative(repoRoot, envFile)}`);
  return merged;
}

async function installDeps() {
  const yes = bailOnCancel(
    await confirm({
      message: "Run `npm install` for the root + workspaces now?",
      initialValue: true,
    }),
  );
  if (!yes) {
    log.warn("Skipped install. Run `npm install --workspaces --include-workspace-root` later.");
    return;
  }
  log.step("Running npm install (this can take a couple of minutes)...");
  const res = await exec(
    "npm",
    ["install", "--workspaces", "--include-workspace-root"],
    { inherit: true },
  );
  if (res.code !== 0) throw new Error("npm install failed");
  log.success("Dependencies installed.");
}

async function buildAgentImage(env) {
  const yes = bailOnCancel(
    await confirm({
      message: `Build the agent Docker image now (${env?.AGENT_IMAGE ?? "rca-agent:latest"})?`,
      initialValue: true,
    }),
  );
  if (!yes) {
    log.warn("Skipped build. Run `npm run docker:build-agent` later.");
    return;
  }
  log.step("Building agent image — this downloads Node + ttyd, takes 2-5 minutes the first time.");
  const res = await exec(
    "docker",
    [
      "build",
      "-t",
      env?.AGENT_IMAGE ?? "rca-agent:latest",
      "-f",
      "docker/agent/Dockerfile",
      "docker/agent",
    ],
    { inherit: true },
  );
  if (res.code !== 0) throw new Error("docker build failed");
  log.success("Agent image built.");
}

async function maybeStartDev() {
  const choice = bailOnCancel(
    await select({
      message: "All set. What now?",
      options: [
        { value: "dev", label: "Start dev servers (backend + frontend)" },
        { value: "exit", label: "Exit — I'll run `npm run dev` myself" },
      ],
      initialValue: "dev",
    }),
  );
  if (choice === "exit") return;
  log.step("Launching `npm run dev` — Ctrl+C to stop.");
  await exec("npm", ["run", "dev"], { inherit: true });
}

async function main() {
  console.log();
  intro(color.cyan("Remote Coding Agents · setup"));
  note(
    [
      "This script will:",
      "  1. Verify Node and Docker are ready",
      "  2. Create or update .env",
      "  3. Install npm dependencies",
      "  4. Build the agent Docker image",
      "  5. Optionally launch dev servers",
      "",
      "You can skip any step.",
    ].join("\n"),
    "what happens next",
  );

  const okNode = await checkNode();
  const okDocker = await checkDocker();
  if (!okNode) {
    cancel("Install Node 20+ and re-run.");
    process.exit(1);
  }
  if (!okDocker) {
    log.warn(
      "Docker is required to create sessions. Setup can continue (you can install/start it later).",
    );
    const cont = bailOnCancel(
      await confirm({ message: "Continue without Docker for now?", initialValue: true }),
    );
    if (!cont) {
      cancel("Install/start Docker and re-run.");
      process.exit(1);
    }
  }

  const env = await configureEnv();
  await installDeps();
  if (okDocker) {
    await buildAgentImage(env ?? undefined);
  } else {
    log.warn("Skipping agent image build because Docker is unavailable.");
  }
  await maybeStartDev();

  outro(color.green("Done. Open the app at " + color.cyan(`http://localhost:${env?.CLIENT_PORT ?? "5173"}`)));
}

main().catch((err) => {
  console.error("\n", color.red("setup failed:"), err?.stack ?? err);
  process.exit(1);
});
